hostname
duid
persistent
vendorclassid

option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu
option host_name
option ntp_servers

require dhcp_server_identifier

slaac private

interface eth0

interface eth1
nooption domain_name_servers
nooption domain_name
nooption domain_search
